version: "2"
services:
  web:  
    build: .
    container_name: api-car
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-apicar
    ports:
      - "27017:27017"