
import * as mongoose from 'mongoose';

export const OwnerSchema = new mongoose.Schema({
  //id: autogenerated
  name: { type: String, required: true },
  purchaseDate: { type: Date, required: true }
});
